### ISSUE TITLE
Add source/citation to reports

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#117]
Ideally all report pages on the website, and all downloaded reports, should show an audit trail, e.g. "Pantheon report generated from database version XXX on dd/mm/yyyy”.

**Comment by johnvanbreda** [comment]
We could add this text to all output reports on screen - I suggest it is added to the top of each report under the title?
Adding to downloads would require a few hours work on the warehouse to change the generic download code, since it doesn't support adding anything other than the information extracted from the database.

**Comment by johnvanbreda** [comment]
Done. It will be included in PDF files as well when these are configured.
