### ISSUE TITLE
Bug in search function in Lexicon

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#120]
The Lexicon search system has a bug, e.g. a search for “wetland” produces the following results:
- Search term “wet*” returns a table with one row containing “AcidFid”.
- Search term “wetland” returns a table with one row containing “AcidFid”.
- Search term "*wet*" returns no results.
- Search term “wetlands*” returns no results.

**Comment by johnvanbreda** [comment]
If you click on the AcidFid term to view its details, you'll note that the body text contains the word wetland. That explains the first 2 points. 
I could not reproduce the 3rd point - it returned the same as wet* for me which is correct because the view is configured to do a "contains" search.
Wetlands* does return results, e.g. click on c and you should get the Coastal term.

**Comment by kitenetter** [comment]
I think the issue here is that the user expected the search box to return all relevant terms, regardless of which alphabet page they are on. As it stands I'm not sure the Search box adds much that is useful, and runs the risk of confusing users who expect it to search the whole Lexicon.

If we keep it, can we re-label it as:
Search (click on alphabet links to see results for each letter page)

**Comment by johnvanbreda** [comment]
I've changed the Lexicon so the default view is all terms, rather than those starting a. Therefore if you load the lexicon then search for, e.g. 'wet' it will search across the entire Lexicon. It only filters to a letter if you choose to click on a letter. I think this is an OK solution?

**Comment by kitenetter** [comment]
Thanks, that seems much better.
