### ISSUE TITLE
Miscoding of "snow bed" species

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#121]
The trait with name "snow bed" occurs twice in the database, once with ID 297 and once with ID 298. The species linked to 298 appear to be correct, but the species linked to 297 include some that are restricted to warm microclimates in the south.

Is this a consequence of the category labels getting moved around?

Are there likely to be other similar miscodings?

**Comment by HDean** [comment]
@kitenetter 
The species that are linked with Trait_ID 297 are incorrect - it looks like a coding error due to multiple traits being in the same column in the original Excel spreadsheets (these species have been double coded - one for the correct trait and an additional one for snow bed).
I'll remove these from the Access database so will show up when the data are next loaded (in the next couple of weeks).

**Comment by HDean** [comment]
Updated in Access database. Changes won't be seen online until data reloaded.
