### ISSUE TITLE
"Broad resources" display duplicated

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#134]
@HDean we have the broad resources hierachical display duplicated here:
http://www.brc.ac.uk/pantheon/content/broad-resources

Should the lower one (under the OSIRIS heading) be removed?

**Comment by HDean** [comment]
Hi @kitenetter 
I see what you mean. The duplication is there because the second set of hierarchies (under the OSIRIS heading) was an example created by Jim Bacon to demonstrate a different way of showing the hierarchies as some of them are so big that the text on screen gets very small. Although I liked this way neither Jim nor I had time to change all of the hierarchies to this more interactive view.
Rather then remove, perhaps we could hide it? Or perhaps we change the heading to something like "Broad resources - alternative view (under development)".

**Comment by kitenetter** [comment]
Yes, let's keep it and update the heading. Not sure we need to say "under development", it sounds like it's an alternative that we may extend in future but unlikely to be be any short-term development?

**Comment by HDean** [comment]
@kitenetter 
It is unlikely that it will be done within the next few weeks but I would like to think that it can be done in the next FY (perhaps wishful thinking!).
However, I don't see a problem with removing "under development".
I was going to update the heading but it must something that Jim embedded as I can't see the title or these alternative diagrams when I edit the page.

**Comment by HDean** [comment]
Hi @johnvanbreda 
Is the above something you can do? On this page, http://www.brc.ac.uk/pantheon/content/broad-resources, there are two versions of the hierarchy diagrams. The second one needs the heading changing from "Osiris broad resources" to "Broad resources - alternative view".  I don't seem to be able to edit it. Thanks.

**Comment by johnvanbreda** [comment]
Done
