### ISSUE TITLE
SAT "Rich flower resource" missing?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#143]
As far as I can see, the Rich Flower Resource SAT (Trait ID 17) is not being included in the SAT tables.

**Comment by johnvanbreda** [comment]
I've checked the data. The Rich Flower Resource SAT is nested directly beneath a broad biotope rather than a habitat (in the case I inspected it was the open habitats biotope). The report query joins biotope > habitat > sat, so excludes the rich flower resource SAT. 
I am not sure if the structure is wrong in the data or the query should be corrected to include SATs that are children of biotopes.

**Comment by HDean** [comment]
Hi @johnvanbreda , @kitenetter 
I've checked my database and the structure is correct. There are three SATs that are nested directly undernearth a biotope. These are:

F001	scrub edge
F002	rich flower resource
F003	scrub-heath & moorland

And they are all nested under the F1 open habitats broad biotope. Is it easy to update the query to show these as well?

**Comment by johnvanbreda** [comment]
Fixed.
