### ISSUE TITLE
Add limit to Coastal Grazing marsh score

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/Pantheon#16]
Threshold of 10 or more species needs implementing in the calculation of the Species Conservation Score in the Buglife Coastal Grazing marsh ranking system.

**Comment by johnvanbreda** [comment]
Can you add an example link please. Do you mean that this score should not be calculated if less than 10 species scored?

**Comment by DavidRoy** [comment]
You are right that the score should only be calculated if species scored < 10.  I'm not sure there's example data in the system to give a link

**Comment by johnvanbreda** [comment]
Estimate 1-2 hours - I think that should read "only be calculated if more than 10 species scored".

**Comment by johnvanbreda** [comment]
@hdean Please can I have a clear explanation of the change required for this. On the Habitat scores page (formerly HORUS) I can click Further Analysis to view the breakdown, e.g. http://www.brc.ac.uk/pantheon/horus/choose-indices?dynamic-sample_id=545483. There are 2 items in the list for grazing marsh - one is subtitled "species" and one subtitled "salinity". **Are they both to be affected by this change?** 
If I click grazing marsh - species, then there is a breakdown for the number of species in each grade. **Does the threshold of 10 need to be met for each grade separately, or does a combined total of more than 10 mean that this scoring can be shown?**. i.e. if I had 6 at grade 1 and 12 at grade 2, would the breakdown of grades show both the grades, or only grade 2?
In this example I am assuming that the grazing marsh entries in the breakdown list would be completely omitted because the total number of species scored is less than 10.

**Comment by HDean** [comment]
@johnvanbreda 
I've emailed David H to find out. The limit of 10 applies overall rather than at different grades but I am not sure what the two different scores (species or salinity) are and whether the limit applies to both or just one. 

It has also highlighted that the information I have about this index and available via the About pages only describes one thing and there is no mention of a split between species and salinity.

**Comment by HDean** [comment]
@johnvanbreda 
So the two scores - species and salinity - are reported differently. The Species scores are calculated a bit like the SQI. Add up all the Species scores, divide by the number of native taxa.
The Salinity scores is calculated simply by totting up the number of scores (no division).

The limit applies to both Species and Salinity scores.

However! The reply I got back from David H suggests that the limit is 10 samples (i.e. species lists from 10 samples pooled together). As Pantheon works on a single sample basis (which might be a pooled list, might not but Pantheon doesn't know), I am not sure how this limit can be incorporated.

**Comment by HDean** [comment]
@johnvanbreda 
Although species and salinity are separate scores and calculated different, they should be reported together.
The limit applies to 10 samples which someone would need to combine themselves before loading into Pantheon. So is there a chance that a warning can be put on the report page, to state that the results are only meaningful when the species list is a combination of 10 or more samples?

**Comment by johnvanbreda** [comment]
@HDean Ok, now I've looked at this again I think the Habitat Scores section needs a bit more work and thought about the UI. At the moment when you click on Habitat Scores you get a page with 2 very simplistic values (number of species and number with habitat scores). You have to click "Further Analysis" even though you've not done any real analysis yet, then this just shows a basic list of scores available. I would prefer to see more output available for less clicks.

One idea would be to create a single output page with all the habitat scores. You would have a table with a header showing the total species count and total species with habitat scores. Then under this would be a list of all the available scores, with the score name in the left column and the score output in the right column. 

Some of the outputs are simple calculations (like the grazing marsh scores) and others are a distribution of values in a set of categories. These could be output as text or even possibly a small bar chart. So the example output might be:

**Number of species**: 100
**Number of species with habitat scores**: 80
----------------------------------------------
**Acid mire**: 3 A, 4 B, 5 C
**Coarse woody debris**: 2 a, 1 a/b, 3 b, 3 b/c, 4 c, 2 c/d, 1 d, 0 d/e, 0 e
**grazing marsh - species**: 15
etc

How does that sound?

**Comment by HDean** [comment]
I agree, this habitat scores need some work.
What you propose sounds good but I would also like to include some more information about the scores/grades.
For examples, Acid Mire fidelity scores:
Grade A - acid mire obligates
Grade B - acid mire specialists
Grade C - acid mire preferential

**Comment by johnvanbreda** [comment]
I don't have those extened terms in our copy of the database, we just have A, B or C. Where would I get the required labelling from?

**Comment by HDean** [comment]
The definitions I have are detailed here: http://www.brc.ac.uk/pantheon/content/habitat-scores

**Comment by johnvanbreda** [comment]
Thanks Hannah. I'm working on this by setting up a lookup table in the database. Whilst doing this I noticed our calcareous grassland data has the following values:
"Unknown"
"Low"
"Moderate to low"
"Moderate"
"High"
The unknown and moderate to low categories are not described in your text.

**Comment by johnvanbreda** [comment]
A couple more points:
1) I don't have a native/non-native flag in my copy of the UKSI data. Therefore I can't limit the count of species used in the coastal grazing marsh score so have currently just included them all.
2) For the exposed riverine sediment (Sadler & Bell) I am simply ignoring most of the values as they are greater than 3 - is this correct? If so are they needed in the database? So, for example if I have a set of scores [1,2,3,4,5,6] I would do the following (1+2+3)/3*100 - the division by 3 is because only 3 of the 6 scores are actually counted. In a real world example, for sample 471276 which is the biggest, there are 111 scores of this type but only a single value 3 which gets counted. So the maths is simply (3)/1*100 = 300.

I've now updated the habitat scores output as suggested.

**Comment by HDean** [comment]
@johnvanbreda 
Thanks for the pointers about the calcareous grassland index - I've checked the documentation I have been sent and there is only definitions for High, Moderate and Low.
Coastal Grazing Marsh scores - I would have thought that if non-native species were not to be included then they wouldn't have been given a score! Who knows! I guess this is something to look into next FY.
Exposed Riverine Sediment (Sadler & Bell) - I think your assumption is correct. We leave it for now and perhaps revisit these next FY.

**Comment by johnvanbreda** [comment]
Ok, thanks @HDean, does that mean this issue can be closed?

**Comment by HDean** [comment]
Yes!
