### ISSUE TITLE
Reload to Pantheon after updates to data

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#166]
The data will need to be reloaded to Pantheon after new data and traits have been added and errors corrected.

**Comment by kitenetter** [comment]
Will we also be able to increment the Pantheon version number?

**Comment by HDean** [comment]
Yes, we will increment the version number.

**Comment by johnvanbreda** [comment]
@hdean, is there more work to be done on the next version before we load it, or is it ready to be loaded?

**Comment by HDean** [comment]
@johnvanbreda 
Not yet ready! I think we are looking at end of Jan before we are ready (I am waiting for updates to come in from a review of the bug data).

**Comment by DavidRoy** [comment]
@andrewvanbreda and @johnvanbreda could you give me an estimate of when the loading will happen, and whether you need anything further from us

**Comment by andrewvanbreda** [comment]
@johnvanbreda When do you think you will be able to this? I can probably work to any date as long as it isn't this week. So earliest is early next week as I can do the importer changes for then. However, I am unsure when John can do his bit (I am also unsure of how much he has to do).
I do not think I will need any further information.

**Comment by johnvanbreda** [comment]
@andrewvanbreda I think it would be a good idea for you to come here - either Monday, Thursday or Friday would be OK? It will just be a case of running your scripts first on the dev server, checking then repeating on live.

**Comment by andrewvanbreda** [comment]
@johnvanbreda I can do that. I need to do the programming first. I could do for Monday if it was really urgent. So let's aim for Thurs next week.

**Comment by andrewvanbreda** [comment]
@DavidRoy @johnvanbreda 
Hi,
In order to load the latest data into the Pantheon database schema, I have to make the following changes on my machine, can you advise a fix? For now, I am just removing the affected rows.
1. 
I have removed this species table row for now.
16255	
Tonicella marmorea	NBNSYS0000024372	Tonicella marmorea	(Lefebvre, 1835)

The preferred_tvk column has this note in it.
“Change species to Thaneroclerus buqeti (Tonicella marmorea is a marine mollusc).	Mollusca”
Are you able to provide a corrected row?

2. I have had to remove the speciesTrait row with ID 204014, the species ID 16255 is not in the species table

**Comment by johnvanbreda** [comment]
Hi @andrewvanbreda, NBNSYS0000024372 is the correct taxon version key for the beetle Thaneroclerus buqeti. Are there any traits pointing to this species table entry? I think it would probably be safer to remove it for now as you have done until someone can review the underlying Pantheon data.

**Comment by andrewvanbreda** [comment]
@johnvanbreda 
Ha, I have just seen what I have done. In point two I have removed the trait for that species. I didn't notice that. It is just that one trait.
For now it is correct that I have removed both rows as I have no confirmation as to the correctness of either

**Comment by kitenetter** [comment]
SpeciesID 16255 (currently with PreferredName as Tonicella marmorea) should be removed.

SpeciesID 16243 (currently with PreferredName as Thaneroclerus buqueti) should be retained.

The single trait associated with SpeciesID 16255 should also be removed (as you have done).

As far as I can see the only trait attached to this beetle is a rarity score of "1", which indicates a common species. But there are no records on NBN, and since it is listed in DAISIE with a map of several continental countries (but no UK) I guess it is a non-native that must have been recorded at least once. 

Some species have a rarity score of zero, was that used for non-natives? If so then perhaps Thaneroclerus buqueti should be zero, but I can't remember what the rules were for this.

**Comment by andrewvanbreda** [comment]
@kitenetter The import was completed yesterday, looks like it went fine.
16255 was removed, 16243 was present as you described
Afraid I can't comment on the correct use of the rarity score and data rules for Pantheon, perhaps someone else will be to comment on the correctness of this.
John should be able to advise when he is happy for this thread to be closed.

**Comment by johnvanbreda** [comment]
It's complete as far as I'm concerned so I'll close it. Please raise additional issues if any problems are found tin the data.
