### ISSUE TITLE
Extended filtering to cover traits/assemblages etc

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/Pantheon#18]
Extend the iRecord explore filter to allow filtering by information within Pantheon - such as specific assemblage types, traits

**Comment by HDean** [comment]
I may have go the wrong idea about the filtering

**Comment by johnvanbreda** [comment]
With reference to the Species Index, the top row of the grid allows filtering, for example type DW into the BAT code column then press Tab to apply it. But, there is an issue on the warehouse which means filters against more complex columns such as the specific biotope (which aggregate the output from several attributes) result in the grid failing to load. See https://github.com/Indicia-Team/warehouse/issues/179. I should be able to get this fixed in the near future and I've set the milestone for this issue to the next release of the warehouse.

**Comment by johnvanbreda** [comment]
The warehouse bug has been fixed and deployed so this now works.

**Comment by johnvanbreda** [comment]
Note that this issue now refers only to the original request "Extend the iRecord explore filter to allow filtering by information within Pantheon - such as specific assemblage types, traits". Other aspects of the species index will be tracked in #32.

**Comment by HDean** [comment]
Everyone is happy with the filtering so this issue can be closed.
