### ISSUE TITLE
Associated species data needs adding

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#27]
Currently waiting for updated data from David Heaver

**Comment by andrewvanbreda** [comment]
Although this is an estimate, there are several points I wish to make about this area. 
- In the example date, I am not sure what the "Trait Value Other species is field" is used for. For instance, if it contains the word "plant" then we can already get this information anyway as we know what the Other taxon is.
- I am not quite sure I fully understand the way the example data works at the moment. However what I would say is that data loading wise this would not be very difficult.
  If needed, we can create a table, and then simply write a script to load the data into it.
  The format of the table would be slightly different to your example data as it would contain IDs rather than plan text.
- I am slightly confused by the example data, the lines list associations between species, but it doesn't say what the association is between them.
  Am also confused why there are 3 species on each line e.g. "Acroclita subsequana", "Euphorbia paralias", "Euphorbia portlandica"
- Although I have said the data loading would be straightforward, that doesn't mean whatever requirements there are to use that data inside Pantheon itself would be simple. Any functionality in the system itself I would imagine would be handled by John as he has written most of the site so far (he might even do the import of associated species, as it won't be related to the previous pantheon importer)

-It would be useful if the data provided to load could use taxon version keys instead of the names, then the precise species are much easier to lookup.

-When you say the links could be made to plural species or taxon groups I am currently uncertain what you mean. 
Does this simply mean there will be separate associations to all the species in a taxon group or does it mean the taxon group would be referred to in one association.
This is important, as if the latter is the case then things are more complex because we might need separate database tables for different kinds of associations.

-Although we have so far spoken about this as being a new database table(s), the requirement seems similar at least to something I am already seeing in the indicia database called "taxon_relations".
Although I haven't used this area, it seems to allow a taxon meaning to be associated with another taxon meaning, and includes a type field to say what the relation is. 
Here again is an important note to think about, as the previous import was based on a the preferred taxon then I think we make the assumption that species with the same meaning use that trait too (if I remember correctly). This is OK to do inside Pantheon as we can just tell pantheon that is how the data works.
However, as (I think I am correct in thinking)  the species associations will be a general indicia enhancement, then I think perhaps the associations should be be meaning to meaning as that would be a cleaner way to orgnanise the data, we can't really make assumptions on general enhancements . So perhaps this points towards using the existing taxon relations also?

Anyway, purely in terms of data loading time. The actual loading of the data wouldn't be too long. I think more of an issue is that there would be significant discussion time on how best to do it.
So taking a guess, I think around 4 days of time (excluding any time taken to enhance Pantheon to actually use that data). This would vary depending on the answers to some of the points I made.

**Comment by DavidRoy** [comment]
For estimating time, please work on the assumption that the data will fit into the existing Indicia data model for handling interactions.  We can then ensure that the Pantheon data is in this format prior to loading.

**Comment by andrewvanbreda** [comment]
OK sure.

If you supplied some data, and it was suitable to load into into the existing taxon relations functionality then in theory it could be quick. However I am not sure how often this functionality is used, so I suspect there would still be some coding.
I think it would be something like 1.5 days in that scenario.

Simply put
1.5 days if we can fit it into the existing Indicia Data Model
4 days if we can't
+
Extra enhancement time for Pantheon to be able to use the new data

However I would approach the assumption we could use any built-in functionality for this with some caution.
 I think I would need to better understand the nature of the requirement for having associations to things like taxon groups. I cannot tell if this would fit into the indicia data model at the moment. Also why there appear to be 3 taxa in the association and also why there is no indication of what the association is in the data I saw.

**Comment by HDean** [comment]
The data that Andy has seen is an excerpt of the spreadsheet sent to me by David Heaver. To answer Andy's queries:
- "Trait Value "Other species is" field" - this field will have a value of plant, animal or fungi, and it could be derived from the associated taxon. However, sometimes the associated taxon is not known, all that is known is that a species is associated with, for example, animals.
- The three species on a line - Species 1 is associated with Species 2 and Species 1 is associated with Species 3 (but Species 2 is not necessarily associated with Species 3). e.g. _Acroclita subsequana_ is associated with _Euphorbia paralias_, and _Acroclita subsequana_ is also associated with _Euphorbia portlandica_. If I had had time I would have modified the list to have _Euphorbia paralias_ and _Euphorbia portlandica_ on separate lines (so there would only be two species to a line).
- TVKs can be provided instead of /as well as species names.
- sometimes a species is not defined in the associated species/taxon field. It may refer to a family (e.g. Asteraceae) or an order (e.g. Lepidoptera). The taxon group is referred to in one association.
- There is no definition of what the association is. All that I have been provided with is that Species 1 is associated with Species 2.

Could you tell me what the exisiting Indicia Data Model is for taxon relations. I can then see how easy it would be to update the existing spreadsheet to fit with the existing model.

**Comment by andrewvanbreda** [comment]
Yes the current Indicia model is quite simple.
Each "taxon relation" consists of a two taxon meanings and a relation "category" between them to describe the relation. 
Each of these 3 fields is required.

I believe the model would be OK for storing relations with a Family or Order as these are just levels in the taxon hierarchy, however the taxon group is stored differently so would be more troublesome.

It wouldn't be a problem if you have situations where a species is associated with more than one other species, but those species themselves are not associated with each other.
That would be represented as several two species relations.
e.g.
Species 1 associated with Species 2
Species 1 associated with Species 3
It would be quicker to write an importer if the input data is organised in this way.

I would be interested in knowing John's thoughts, particularly if there are general enhancements to the Indicia design it would be good to get as many opinions as possible.
I am almost certain he would have some useful input on this topic, particularly as I haven't used the relations area, I am going by what is in the database. It might not even be in use anymore.

**Comment by johnvanbreda** [comment]
I think there's a little background on the "existing model" aspect of this. The original Indicia data model did not support associations of this nature. However, there was a taxon_relations table, intended to allow backtracking through taxonomic changes (lumping/splitting, aggregates etc) since this was a requirement of one of the early projects. It's quite a simple table as Andy says.

Since then, we've implemented a more thorough database update to support _occurrence_ associations. These are intended to support the recording of ecological interaction observations, e.g. I saw a fungus growing on the trunk of a tree, causing tree decay etc. We don't currently have an equivalent table for supporting interactions in the species data, though in my opinion they are really the same thing except for the fact that you are recording generalised interactions that you often see in a species, rather than a specific observation of that interaction. So I'd propose that we clone the data model that exists in the occurrence associations table. This gives us the ability to record:
- from species
- to species
- association type (picked from a controlled list, e.g. preys upon, parasitises)
- part (picked from a controlled list, part of the organism that is being interacted with, e.g. leaf, flower)
- position (picked from a controlled list, e.g. on or under)
- impact (picked from a controlled list, e.g. causing decay)
- comment

All the controlled lists are things you can change to match your dataset.

**Comment by johnvanbreda** [comment]
Output for the associations: A table of each associated species pulled out of the sample. 2nd column is the number of associated species that were found in the sample.

**Comment by johnvanbreda** [comment]
Refined requirements from @HDean:
The other day I had a meeting with David Heaver about the associated taxa data for Pantheon and we have now come up with ideas on what we would like the associated species output to contain. It would be great to have your feedback on this and how the data should be structured as there was talk about using some existing set up within Indicia to do the associated taxa.

Attached is a spreadsheet that contains the associated taxa data. There are 5 columns:

ID = ID field.
SpeciesName = species name.
AssociatedTreeType = where the associated taxa is a tree/trees, this states whether they are broadleaved, coniferous or both. Where there is no other data this means that the species is associated with broadleaved woodlands, coniferous woodlands, etc. Not exactly sure how this will fit in to the reporting side of things.
AssociatedTaxaType = states if the associated taxa are animal, plant or fungi.
AssociatedTaxa = the name of species or taxa which is the associated with the species in the SpeciesName column.

David would like to see the following output as a minimum:

•         When a sample is input, an associated taxa button produces the following report.
•         A list is provided of the associated taxa and the number of species within the sample that are associated with it. E.g.
o   Quercus – 7spp
o   Betula – 2spp
•         The list is grouped by the Associated Taxa Type, so the above example would be grouped under plant.
•         The output would be ranked with the taxa with the largest number of associations at the top.
•         After the number of species with the associations the different conservation statuses with the species is also shown
o   Quercus – 7spp – 2 NS, 5 NR
o   Betula – 2spp – 1 NR

The above mirrors the reporting for Osiris but instead of broad biotope, it is the associated taxon group. The number of species would also be a hyperlink to the species list. This would be the minimum we would like Pantheon to do.

To take it one step further, David would like to be able to link the species list within each association with the habitats and traits within Osiris. For example:
•         Quercus – 7spp – 2NS, 5NR
o   Heart rot – 3spp
o   Sapwood rot – 1sp

To prevent this getting from getting really messy there would probably have to be some sort of filtering system, e.g. a filter allowing you to choose the habitats such as decaying wood.

**Comment by johnvanbreda** [comment]
As we’ve not yet added associations for species to Indicia, only associations for observations at the moment, there is some flexibility in how we approach this. However in order to be consistent I’d prefer to maintain the list of associations as simply links between 2 taxa, rather than the link from species to a set of 3 labels. In other words your spreadsheet would have 2 columns, species name and associated taxa. Here’s a sample translated from some random rows in the spreadsheet:
Species name                                    Associated taxa
Acroclita subsequana                     Euphorbia paralias
Arctosa fulvolineata                        Arthropoda
Argyra vestita                                    Arthropoda
Anisodactylus poeciloides            animalia
Drosophila subobscura                  Pinopsida

Etc.
That way all the associations are simple links between 2 taxa. We could then group the output either by kingdom which we can determine easily from our copy of UKSI (which links all taxa to their parents up to kingdom).
Note that grouping by kingdom might be incompatible with sorting by number of taxa? Or would the sort only apply within each kingdom’s group? So if the species in my example above were provided in a sample, then the output might be:
Plants
Euphorbia paralias (1 sp)
Pinopsida (1 sp)
Animals
Arthropoda (2 sp)
Animalia (1 sp)

Adding conservation statuses to this sounds OK.

Adding in the traits also sounds OK though a bit trickier - presumably in an extra column. I’d suggest we develop the above first then add this rather than do it all in one go in case this bit is hard to achieve.

Could the filtering be done in the same way as the existing grouped conservation traits idea?

**Comment by DavidRoy** [comment]
Thinking more widely about this requirement, is it possible to have additional attributes associated with the interaction between taxa, e.g. source literature, type of interaction (herbivory, Saprophagous, mining, galling, inquiline).  This would more easily allow DBIF to be integrated.

**Comment by HDean** [comment]
Hi @johnvanbreda 

Grouping by kingdom would be great and the sorting by number would only apply within kingdom. This bit of the associated species would be a priority.

If adding in traits is tricky so that it adds considerably to the time you spend on this, then I would suggest we don't do this - there is still quite a bit to do with higher priority.
Re; filtering,  I was wondering if the output is quite similar to the Osiris outputs, could we filter in the same way (i.e. in the box at the top of the column in the report table?) I think the only filtering would be done on a habitat or trait, rather than combinations of them (like the grouped traits).

**Comment by johnvanbreda** [comment]
New module in warehouse now supports associations between taxa - https://github.com/Indicia-Team/warehouse/commit/9b2d1b90ce19062aa9d56ddb5803327dce967650.

Data import done.

**Comment by johnvanbreda** [comment]
@DavidRoy the current data model was derived from the work done with BMS and includes attributes to cover the type of interaction, outcomes, part of organism/placement etc. It does not include literature source though that could of course be added quite easily.

@HDean There is now an associations button which covers all the requirements except for the addition of traits to the report output. Let me know what you think before I go any further.

**Comment by HDean** [comment]
I am closing this as I think that we have got as far as we will this FY on the associations.
