### ISSUE TITLE
Be able to save and analyse a subset of a sample as a separate sample

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#33]
e.g. select and save heartrot species within a sample, and analyse separately.

Could this be done by filtering?

**Comment by HDean** [comment]
I think this may be covered by #11

**Comment by johnvanbreda** [comment]
On the species list outputs, add a button "add to scratchpad" to add the currently visible list (filtered etc) to the scratchpad.

**Comment by HDean** [comment]
Hi @johnvanbreda 

This is one of the high priority functionality based issues. It is also covered by #11. With reference to my earlier email, this really covers the ability to edit sample lists in a variety of ways rather than just subset an existing sample.

Edits would include:

•	Being able to delete species in the list
•	Amend species names
•	Add species
•	Delete entire lists, or at least mark them as “deleted” and remove from public view
•	Be able to join together multiple lists to create on large one

**Comment by HDean** [comment]
Hi @johnvanbreda , do you have any thoughts on this that I can feed back to Jon? We are not expecting something to be up and running by the end of the month but I think Jon would like to have a plan of action by then.

**Comment by johnvanbreda** [comment]
I've had a think about this requirement and the requirement in #11 and I think the best approach is to enhance the existing "Paste species list" functionality, since this already copes with arbitrary lists, list editing, removing and adding names etc. 
So, my suggestions are:

1. On Explore my samples, under actions, have an "Add to list" link. When clicked, this pops up a dialog allowing you to select one of your pasted lists, or choose a "Create new..." option and type in the name of a new list. If you select an existing list, then the species are appended to the list. An option on the dialog "Open list after saving" can be ticked if you want to navigate straight to the list content.
2. On Explore my records, under the grid of records, have an Add to list link. This works exactly as above, but uses the list of species currently loaded in the reports to add to or create a new list.
3. On the Paste species list page, any existing lists have an Add to list link which allows you to combine the results of one pasted list into another. This works exactly as above, but has an additional "Delete this list" checkbox option which allows you to remove the source list (as opposed to leaving it in existence).
4. On the edit pasted list page, add a delete button.

Do you agree that this covers everything?

**Comment by HDean** [comment]
Hi @johnvanbreda 
Yes, I think this pretty much covers everything and is leaning towards the pasting a list method of data entry which is preferred way for many.
I have a meeting on Thursday with Jon W and I will discuss this with him then to see if he is happy with the above and if there is anything else he would like adding.

**Comment by HDean** [comment]
Adding in comment from John on 7th Dec:

Yes. Having mulled over David’s ideas for a while, I’m coming to the conclusion that a way of temporarily grouping lists is better than a way of permanently combining 2 lists to make a single one. It’s more flexible. Actually changing the reports to support this doesn’t look too hard, so the question is the user interface. Here’s an idea:
1)	Add a second tab to http://www.brc.ac.uk/pantheon/species-lists/my-list, called “Quick analysis group” (I’m sure you can think of a better name!).
2)	In the actions column on tab 1, add a “Add to quick analysis group” action.
3)	If this action is clicked, then the list’s title, description and species count appears in a panel on the next page. So, you can quickly collect together several of your species lists onto this tab. 
4)	On the 2nd tab, each listed item has a “remove” button next to it so you can take them out of the analysis group. 
5)	On the 2nd tab, there is an “Analyse group” button so you can run an analysis on the group. So, the Quick analysis group tab might look like:

X     Basildon meadows [265 species]
Adrian Knowles list

X     Bredon vane trap [49 species]
replicates removed. For testing RIEC 

x      Cowpen Marsh all data [202 species]
                                 inc pond net data

                                [Analyse group]

6)	On the analysis output pages, the page title sample name would be something like “Ecological guilds: list 1 name, list 2 name, list 3 name”. If more than 3 lists, we could call it “Ecological guilds: multiple lists”.

How does that sound?
Cheers
John

**Comment by HDean** [comment]
My reply to the above on 19th Dec:
Hi John,

I’ve had a think about this. It all sounds good – go with quick analysis group as a tab name, I am assuming it is easy to change in the future?
Temporarily grouping sounds like a good idea. Can functionality be added so this can be saved into a new single list?
And finally will we be able to do this with the saved samples? E.g. if you went into Explore my samples, you could join some of them together?
In the “my species lists” page, can we have a button under Actions that deletes the entire list? I think this is something that people really want!
I think it is best that we get something up and running so we can visualise better so if you need a break from the family over Christmas…

Best wishes,
Hannah

**Comment by johnvanbreda** [comment]
Hi @HDean,
This is now functional for scratchpads.
* "In the “my species lists” page, can we have a button under Actions that deletes the entire list? I think this is something that people really want!" - can this be added as a separate issue please?
* For samples, is being able to temporarily combine them enough? Combining them and saving as a permanent new sample would be a bit odd as it creates duplicates and the dates/places might be different. Or, we could perhaps allow several samples to combine to create a single new "pasted list" rather than a sample?

**Comment by HDean** [comment]
Everyone who has been in contact with me about this is is very happy with it. I think this issue can now be closed!
