### ISSUE TITLE
Reload data into Indicia after data cleaning

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#34]

**Comment by andrewvanbreda** [comment]
Estimate
I have made the assumption that the data cleaning is simple, and that there might be some additional resources and some name changes, however the number of layers in the data structure would remain the same.
I think removing the data, making the changes, checking them, and reloading would take around 1.5 days

This might vary wildly depending on the nature of the changes. It wouldn't be less that 0.75 days.

Note that the process will be much simpler if you are able to specify the exact nature of the changes when compared with the existing data as an examination to determine the differences would be time-consuming.

**Comment by HDean** [comment]
Thanks Andy for the estimate. I will be keeping a change log so you can see exactly what changes have been made.

**Comment by HDean** [comment]
Andy - I have assigned this to you but there is nothing immediate for you to do. There will probably be two reloads, one after the data cleaning and then one after the peer review (although these might come close enough together that only one is needed).

**Comment by andrewvanbreda** [comment]
The contract came though for me to sign for this work, but I am wondering do we have exact details of what the changes will involve yet?

**Comment by HDean** [comment]
I'm working on them! There will some changes to the trait names and some changes to the data (mostly errors with synonyms). I will get them to you as soon as poss.

**Comment by andrewvanbreda** [comment]
Hi,

Just wondering how we are progressing with this, as I think when this work was first mentioned I remember a mid-september date being mentioned for the completion of the work...I think anyway

**Comment by HDean** [comment]
Hi Andy,

Still working on the changes! I am hoping to get them done by the end of the week and will send over the updated database, complete with listing of the changes that have been made to the traits.

**Comment by andrewvanbreda** [comment]
OK sure no problem. No particular urgency from my end. I was just checking I hadn't missed anything

**Comment by andrewvanbreda** [comment]
I have identified a couple of questions after a reasonably detailed review of the changes.
Although I was originally going to accumulate all the questions before sending them to you, I have changed my approach slightly. I am going to run the existing importer against the data to see what it does, as looking at the changes I am wondering if the existing importer is intelligent enough to handle a lot of the changes automatically….we will see. I might have some more questions after that process.
1. When I worked on the Pantheon importer previously I worked with 3 tables called tbl_species, tbl_species_trait, tbl_traits
   However last time those tables were extracted out of the database for me. This time I opened the database myself and as such was able to see there are other tables.
   Is it just still the above 3 tables that are relevant to the importer?
   In particular, I see there is a table called qry_synonym_trait_data.
   I am not a great Microsoft Access database expert (it is just one of those applications that I need to dabble with once in a while), but this looks like it is just generated by the system automatically looking at the other tables (hence its name starts with “qry_” rather than “tbl_”).
   Am I correct in thinking therefore I do not need to worry about this table?
   The rule last time was that traits associated with synonyms would just be attached to the preferred species, is that still the plan?
2. The broad assemblage types are now removed and the specific assemblage types are moved into the broad/specific biotope/resource hierarchy. I see that broad and specific assemblage types are still in the traits table, however the specific assemblage types now point at specific biotopes (this is described in your email). I assume that the broad assemblage types should just not be imported. I think I am clear on that.
   However my question is that should specific assemblage types still be called that? Or are they actually now known as resources?
   The problem is that the way the data is currently imported means that the data is split into levels, so simply positioning them under a specific biotope means the system will think it is a resource as the data is currently structured.

**Comment by HDean** [comment]
Hi @andrewvanbreda ,
1. It is the same three tables: tbl_species, tbl_species_trait, tbl_traits. The other two tables are "holding" various bits of data which will probably be incorporated at some point. The queries are there for when I was running some checks on the data I imported. Sorry I should have deleted these!
2. Yes, the broad assemblage types do not need to be imported, However, I should warn you that the species records for the BATs are still in the database. We wanted to keep the data, at least in the Access database, so if we do ever want to go back to them we could.
The specific assemblage types are essentially now a resource (or habitat) but these may need to be highlighted as SATs as they will be reported on separately from the other resources.

**Comment by andrewvanbreda** [comment]
The problem as I can see it is once we import the Specific Assemblage Type as a resource we have no way of knowing by looking at the database that these are specific assemblage types.

So I can currently think of 3 possible solutions, I probably wouldn't make a decision on any of these yet until we have thought about it a bit longer.
1. We could in theory simply leave the data as it is in the database, then tell John which ones are specific assemblage types, then he can hard-code the report.
   This is an easy solution, but not that good mainly because it is troublesome if the data changes.
2. We could put an indication in the name if it is a specific assemblage type. For instance in the resource name "(SAT)" could be written at the end.
   Teh main disadvantage of this is reporting code is slow as it needs to analyse the name
3. Or we could do something in the hierarchy in database. Specific Assemblages could have a parent "Specific Assemblage Type" item
   Although in some ways I feel this is a good solution, in some ways I feel it is a bit too unauthodox to go ahead with.

**Comment by HDean** [comment]
Thanks for the thoughts Andy. I have a telecon tomorrow with Jon and John, where I will mention this and the possibly solutions.

**Comment by andrewvanbreda** [comment]
Actually there is another solution, at some stage I will be adding attributes for terms to the system. This is being done for the Plant Portal project.
We could bring this forward, however there is another disadvantage with this, as it is quite big change to the way the database works, it is long-winded to get it to go live with all the testing etc that it needs to go through

**Comment by andrewvanbreda** [comment]
I have now tested the importer. It actually seems to have handled the changes pretty well (it was always the intention to make the importer as intelligent to changes as possible, but that doesn't mean it will work). I have just 8 problems detected in my list, and almost all those are very minor spelling differences which are probably just a slight inconsistencies between the diagram and import data and are probably fine and not related to the importer itself. There are no serious problems to report. A couple of missing terms, but I will check to see if they are in the import data at all.

More information in forthcoming comments. I will  try and see if I can resolve any issues myself before passing them to you.

**Comment by andrewvanbreda** [comment]
Having analysed the issues, there are some things going on the database that I couldn't see in the main user interface that means I cannot diagnose the problems as easily as I thought I would be able to. However, the following 2 problems look to be caused simply by the import data not quite being the same as the diagrams. You may wish to alter the original database. Let me know if you do as I will need to export the import files from it again.

2 problems that are simply caused by inconsistancies between the import data and the diagrams, nothing is wrong with the importer for these.
1. Under T1 tree associated.
   "Shaded Woodland Floor" in the diagram is called "shaded field & ground layer" in the import data.
2. Under T1->A1 Aboreal,.
   "wet woodland" in the diagram is called "carr/wet woodland" in the import data.

The other 6 issues I discovered I will comment on in due course.

**Comment by HDean** [comment]
Hi @andrewvanbreda,
The diagrams are correct.
Shaded field & ground layer should now be Shaded Woodland Floor
carr/wet woodland should now be wet woodland
I'll update the access database.

**Comment by andrewvanbreda** [comment]
This shouldn't be a problem, as the importer will act on whatever it is given (mostly anyway, with a few exceptions). I have exported the database into excel/CSV files I can import. So it is actually easier for me to just change my import files directly. I will do that now for those two changes.

**Comment by andrewvanbreda** [comment]
I have now supplied John with an importer for v3.7.2

**Comment by HDean** [comment]
Online Pantheon now showing updated data.
