### ISSUE TITLE
Flag up duplicate species during import

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#44]
During import only a distinct list of species for a sample is imported so is this possible?

**Comment by johnvanbreda** [comment]
I think we discussed that the "scratchpad" would only accept a distinct list of species, so this isn't a requirement anymore?

**Comment by HDean** [comment]
When data are imported from a csv file will the species list end up on the scratchpad? Maybe I am misunderstanding what the scratchpad will be. I thought that if you imported a sample, you can then analyse that sample. If you want to analyse a subset of the sample you then use the scratchpad to create a subset.

From what I can remember, a distinct list of species only is imported when loading from a csv. I think what NE would like to do is have some output where it says that Species X was in the sample twice.

**Comment by johnvanbreda** [comment]
If you paste a list of species into the scratchpad, then I'd envisage that this would include the functionality to warn you of duplicates.
If you import a list of records to run an analysis against then having duplicates is acceptable because they might be different grid references or dates so they are different records. But when you do the Pantheon analysis you might like to be warned. Perhaps we should simply display an extra column for the number of duplicates in the "Basic output" at the top of the summary outputs which could be hidden if there are none?

**Comment by HDean** [comment]
Sounds like a good idea. Would the number of duplicates also include a list of the duplicated species names?

**Comment by johnvanbreda** [comment]
Just to be absolutely clear, at the moment if you import a list of 10 records of 9 distinct species, then the report outputs will only act as if you had a sample size of 9. Duplicates are simply ignored.

So, if there are duplicates in the sample, then I suggest altering the output for "Sample size" on the summary panel, so it reads something like "349 (11 duplicates)". If you click on 349 then you see the full species list. If you click on "11 duplicates" then you see the duplicates only.

Does that sound OK?

**Comment by HDean** [comment]
Yes that sounds great!

**Comment by HDean** [comment]
Done
