### ISSUE TITLE
Species Index: re-instate a column called 'published indices (Horus)'

### ISSUE THREAD

**Issue by jonrwebb** [BiologicalRecordsCentre/Pantheon#48]
When new spoke on the phone about this on the 21st Sep I got confused and thought that this was referring to the defunct Horus score. It wasn't,  it refers to species being listed in other published indices which are in Horus. An example would be the Index of Ecological Continuity (IEC) where species are listed as grade 1, 2 or 3. This column should therefore include an 'IEC1' for example, to show a grade1 species. All this info is already present in the Horus outputs.

**Comment by johnvanbreda** [comment]
Hi @jonrwebb. I've not updated the columns on the species list shown for a sample (via the button below the sample summary). I wasn't sure if the columns in this report should match the species index? Anyway, the species list for a sample still has the old HORUS indicator so I've renamed it to Published indices (HORUS). Here's an example: http://www.brc.ac.uk/pantheon/species-for-sample?dynamic-sample_id=471276. Click twice on the column title to sort by the value descending, so you will see the sort of thing it generates on the first page of the report. 
1. Is this the correct information that you'd like me to re-add to the Species Index?
2. Should the sample species list report have exactly the same columns as the Species Index?
3. Where do the abbreviations come from - e.g. IEC. Should I attempt to auto generate them from the index title, e.g. "seepage habitats fidelity score - woodland: B" could be output as "SHFSWB"?

**Comment by jonrwebb** [comment]
Hi John,

This all looks very good.

I wasn't sure if the columns in this report should match the species index? Yes they should. I think if the species list matches the species index it will be easier for people to use them both – they’ll be familiar.
1.  Is this the correct information that you'd like me to re-add to the Species Index? Yes, but I ran a Grimsthorpe  species list through Pantheon and noted that the IEC (revised) was not being displayed. ACTION: Can we check with David Heaver that all his Horus values are correct. There will not thousands of species with these Horus values but in certain sites (dead wood, seepages etc) these older values can be useful.
2.  Should the sample species list report have exactly the same columns as the Species Index? Yes
3.  Where do the abbreviations come from - e.g. IEC. Should I attempt to auto generate them from the index title, e.g. "seepage habitats fidelity score - woodland: B" could be output as "SHFSWB"? I thought that these had already been completed for original Horus work for the 2016/16 build? I am sure David and me talked about it. Anyway, it should not be a big task to rectify ACTION: David, can you please supply John with the abbreviations/ terms to use for Horus?
   It feels to me like there is a couple of tasks for David to Liaise with John to just check that all the correct scores are being displayed ( e.g. IEC) and also that all the terms to be used are correct.
   Thanks

Jon

**Comment by jonrwebb** [comment]
Do you want me to make this a Guthub issue?

**Comment by johnvanbreda** [comment]
Thanks Jon. 
I've now updated the output of the published indices column which I think was incorrect before. IEC is now showing sometimes so I think it's right. I've updated various species list outputs so they are now all the same.
David Heaver has sent me a list of abbreviations. We have a few options as to how we handle these. 
1. We could get Hannah to change all the trait names to match the abbreviations in the original Access DB, so they are output correctly. We could then use the Lexicon to create the flyover hints for the full expanded index name.
2. Hannah leaves the source data as it is, but Andy changes the importer to map the full labels to the abbreviations so the copy in Indicia has the abbreviated form. We could then use the Lexicon to create the flyover hints for the full expanded index name.
3. I could code the mapping into the report code, so the data is changed on the fly to output the abbreviations. We could then either use the Lexicon to create the flyover hints with the full expanded index name, or I could build this into the report code.

So, @HDean do you think it is appropriate to store the abbreviations in the data instead of the full index names?

**Comment by jonrwebb** [comment]
Hi John,

1) I have just looked at the Species Index and as the  'published indices (Horus)' is not there I could not check it.

2) I also looked at the tabular outputs you have created for Osiris. They are very nice but the ‘% return’ value is incorrect ( I think I know what you have done). The value should be ‘% representation’ and it is a measure of:

the number of species typed to resource X in the sample /  the total number of species typed to this resource in pantheon

e.g. If in Pantheon we have typed a total of 100 species to Seepages and we found 20 in the sample the % rep would be 20%
e.g. If in Pantheon we have typed a total of 1000 species to peatland and we found 20 in the sample the % rep would be 2%

It is a measure of how good the site is for representation of a specialist fauna, perhaps better than a basic species count. Is that clear?

Thanks

Jon

**Comment by johnvanbreda** [comment]
Hi @jonrwebb 
1. The column is definitely there. Have you checked that the column is enabled by clicking the + button in the top right of the grid?
2. Ok, I see. Just note that for smaller samples you'll get lots of zeros. I've updated the 3 tabs for the Osiris output. 

Does this calculation of representation also apply to the figures on the main summary tab and anywhere else percentages are given? For example, on http://www.brc.ac.uk/pantheon/pantheon/summary?dynamic-sample_id=471196 the % for adult predator is 57%, because 57% of the analysed species in the sample have this guild. If we change to the new method, then this would output a much lower percentage because it would be the percentage of all species that have this guild which are in the sample?

**Comment by jonrwebb** [comment]
1. ```
     Ah yes – I see the column. Nice 1. The species index is looking very good. Well done.
   ```
2. ```
     Brilliant! I have just been playing with this – looking good. We now have proportional representation, which is great. Don’t worry about the zeros. % Rep comes into its own if you look at the sample form Gibraltar point , which is a saltmarsh site. If you just look at the count values for mineral marsh and saltmarsh on the tabular habitats output then there is more mineral marsh species BUT if you look at the % rep then you can see that proportionally, there is far more saltmarsh species. I am very pleased with this. Now looking forward to seeing the conservation values go into to another column….then I have enough data in one place to analyse site quality.
   ```

Does this calculation of representation also apply to the figures on the main summary tab and anywhere else percentages are given? For example, on http://www.brc.ac.uk/pantheon/pantheon/summary?dynamic-sample_id=471196 the % for adult predator is 57%, because 57% of the analysed species in the sample have this guild. If we change to the new method, then this would output a much lower percentage because it would be the percentage of all species that have this guild which are in the sample? NO. The main use for the %rep is for quality analysis, which is not needed for the predator value as we don’t use this to assign site quality.

I am very pleased with progress so far.

**Comment by jonrwebb** [comment]
Hi John,

You are probably aware if this as I expect things are in prep: I went on today to look at an Osiris output and noted that the conservation status was now up and running (great) but it was producing very odd outputs (samples of 100+ species only analysed c.10)

Just so you know

J

**Comment by johnvanbreda** [comment]
No problem - I'm working on that right at the moment.

**Comment by johnvanbreda** [comment]
Sorry, didn't mean to close this!
@jonrwebb The conservation statuses in the species index report (and sample species) have a filter applied to the designation, so that only designations with IUCN in the original designation title will show up. This filter is not applied to the tables generated for Osiris at this point in time. 
1. Is this filter correct?
2. If so then I presume it should apply everywhere the conservation statuses are shown.

**Comment by jonrwebb** [comment]
Hi John,

No the filter is not correct. Conservation designations have got a bit convoluted as we have old designations and new designations. I will attempt to clarify:

·         Where the new designation exist, these should trump the old ones (the old ones should not be displayed and neither should species that are now downgraded to no status) (see appendix below)

·         All current designations should be displayed. This will often mean two or more displays for some species (see appendix below)

·         Also in this column are abbreviations for species protected by law (such as Limoniscus violaceus) and priority species on the s41 list. All of this info should be displayed on the Species Index & Osiris Sample and there should be abbreviations for these categories.

·         The actual conservation abbreviations used in the table look wrong and convoluted. I thought we produced some new ones – perhaps not. Do you have  a list of what you are currently using so that I can check them? I would like these to be clearer.

I am away Monday next week, but in on Tuesday.

ACTION: Can you send me your current list of abbreviations so I can amend on Tuesday. David found this list fo designations. If this is still correct (the yellow highlighted ones) then I will use this to come up with better abbreviations.

ACTION: There is a ‘marker’ that points to taxa that have new designations so it should be easy to mark these and hence trump the old designations…but I will have to talk to Hannah to tell you what these are.

APPENDIX (just so you know):

Old and New Conservation Status
The old way used ONE system that went as follows:
N (Nationally Notable)
Nb (Nationally Notable B)
Na (Nationally Notable A)
RDB 3 (Red Data Book 3 Rare)
RDB 2 (Red Data Book 2 Vulnerable)
RDB 1 (Red Data Book 1 Endangered)
In a perfect world these would not display if a new review has been completed. In these instances some species that did have a designation now have none. We do have a list of all those taxa that have been reviewed.

The NEW way uses TWO systems:
System ONE  - A Great Britain rarity Status:
NS (Nationally Scarce)
NR (Nationally Rare)

System TWO – IUCN red listing:
NT (Near Threatened)
VU (Vulnerable)
EN (Endangered)
CE (Critically Endangered)
DD (Data deficient)
CE (PE) (Critically Endangered  - possibly extinct)

So, a species under the new system can be NR; CE

Thanks

Jon

**Comment by johnvanbreda** [comment]
Hi Jon
The difficulty here is that the database is currently loaded with designations information from the UKSI which is based on the JNCC designations spreadsheet. Since we only have one set of designations per species list, we'd ideally want to update the JNCC spreadsheet and therefore UKSI rather than just use our own. I think we discussed this a couple of months back with David but I'm not sure what the outcome was.

Here's a dump out from the database of the current list we are using. I've only included any which are designated against at least 1 insect. The format is a raw dump so if you need help converting to a spreadsheet let me know.
[insect designations.txt](https://github.com/BiologicalRecordsCentre/Pantheon/files/502981/insect.designations.txt)

**Comment by jonrwebb** [comment]
Hi John,

Yes I did talk about this we CEH and we came to the inclusion that we would use our spreadsheet. The JNCC list is not great, out of date and has errors within it.

Although I appreciate that we should all be using the same source material I would like us to move ahead with our up-to-date spreadsheet  - perhaps this will push JNCC to come to us and update their system with our info.

We can talk to Hannah (and David if needs be) next week. I know that Hannah has done some work on the designations, and perhaps the confusion is that she has not passed this onto you yet.

We can catch up on Tuesday and will sort this out next week.

Kind regards

Jon

**Comment by DavidRoy** [comment]
Yes, there is an issue for this already - #36.  On @HDean's to-do list.

**Comment by johnvanbreda** [comment]
@DavidRoy if we decide to use this new spreadsheet, do we replace the existing JNCC designations loaded up from UKSI? Will this be a complete replacement, or a partial one?
The data model doesn't currently support "sets" of designations, though designations do have a category applied to them so potentially we could ensure the new designations have different categories and use this to filter them from the old UKSI supplied designations.

**Comment by DavidRoy** [comment]
My initial reaction is replace.  But do you know of Indicia applications that use the version we currently have?  As Jon says, the version that he has collated is likely to be the 'best'.  We can then have a discussion with JNCC/UKSI etc about the best way forward.

**Comment by HDean** [comment]
Hi @johnvanbreda, @jonrwebb,
1. I have the conservation designation data and it is on my to-do list today (possibly tomorrow!).
2. "do you think it is appropriate to store the abbreviations in the data instead of the full index names?" Usually I would store as the full name (especially as I have not (yet) created a companion document for the Access database where I would provide keys to abbreviations) but if it makes it easier/more efficient to store as the abbreviations, then I would be happy to update it. Just let me know what is easier for you, John. And if you do want me to update the database, could you provide me with David H's abbreviations as I don't have a copy. Thanks.

**Comment by johnvanbreda** [comment]
@DavidRoy No, we aren't making use of the designations other that ERCISS who use designations info on their reporting server as a filtering option. It is also possible to do this in iRecord now using the What tab on the filter builder, but its a bit tricky unless you know what designation you are looking for. 
ERCISS are using their own warehouse so if we update only our designations then it won't affect them.

Are the designations provided for Pantheon going to be invertebrate only rather than a complete set? It might be challenging to integrate an invert set, especially if 1 designation covers both inverts and non-inverts.

@HDean I've attached David H's document below. 
Regarding storing abbreviations vs full names, I don't mind if you prefer to keep full names in the database. Its just that as we have a lexicon which works by expanding short versions into longer descriptions, it seems a shame not to use the same approach. I think therefore that I would suggest that we update @andrewvanbreda's importer to convert the full names to abbreviations in our copy of the database so you can leave yours as it is.

[HORUS indices for David done.docx](https://github.com/BiologicalRecordsCentre/Pantheon/files/506018/HORUS.indices.for.David.done.docx)
