### ISSUE TITLE
Species Index: delete duplicate rows (species) when filter applied

### ISSUE THREAD

**Issue by jonrwebb** [BiologicalRecordsCentre/Pantheon#50]

**Comment by johnvanbreda** [comment]
The reason we get duplicates is the query is set up to output 1 row per combination of species and biotope, rather than 1 row per species with the biotope information all combined into one cell. For example, currently we get:
**Species | Broad biotope | Specific biotope**
Abdera affinis | saproxylic | conifer or broadleaf
Abdera affinis | saproxylic | fungal fruiting bodies

We could alter the query to output the following:
**Species | Broad biotope | Specific biotope**
Abdera affinis | saproxylic | conifer or broadleaf;fungal fruiting bodies

Things might be slightly more complex if there are examples with 2 broad biotopes, since joining the biotopes like this will mean it won't be 100% clear which specific biotopes belong to which broad biotopes. 

Is this approach OK?

**Comment by jonrwebb** [comment]
Hi John,

Yes the second query output is fine, thanks.

I wonder with species with two broad biotopes, can it just be queried in the same way you have described querying the Specific Biotope (habitat) as in…

Species | Broad biotope |
Abdera affinis | saproxylic; wetland |

So it displays all Broad biotopes

**Comment by johnvanbreda** [comment]
Agreed - that's how it works now. E.g. filter for Achanthiptera rohrelliformis.
