### ISSUE TITLE
Clarify Osiris sub-headings or remove 

### ISSUE THREAD

**Issue by jonrwebb** [BiologicalRecordsCentre/Pantheon#53]
sub-headings (such as base status or humidity) need to either be clarified as such or (as Martin Harvey suggested) removed all together. Osiris Tabular and Tabular Hierarchy currently report on 'base status' etc and it may be that we remove these reports, just reporting on the level below. Wait until peer review before making any changes.

**Comment by HDean** [comment]
No decision has been made on this (yet). However, the ability to highlight which of the terms are containers/headings would be useful.

**Comment by HDean** [comment]
@johnvanbreda 
There are several terms within Pantheon that are headings or containers for groups of traits rather than a trait themselves. For the reporting side of things, they are currently considered as traits - these are terms such as humidity, habitats, base status. Is it possible to highlight in some way that these are not traits but the names of groups of traits? These are detailed in the lexicon and in the hierarchy diagrams for the different biotopes but it is not obvious within the reports.

**Comment by johnvanbreda** [comment]
@hdean For the tabular output, I think the best thing is to completely exclude the rows which show just one of the subheadings in the resources. You would then only see the contained resources such as "habitats >> litter & ground layer" so it is clear that habitats is just a subheading as it has no row of its own.
For the hierarchical output I can think of 2 approaches - either to display the subheadings in an italic font but otherwise for it to work as now, or to skip this level out and add the subheading to the level below. So, where you might expand the following sequence of 4 levels:
open habitats | short sward & bare ground | habitats | dung and carrion

In the first option this will still be 4 levels, shown as 
open habitats | short sward & bare ground | _habitats_ | dung and carrion 

In the second option this would show as 3 levels, e.g.
open habitats | short sward & bare ground | habitats >> dung and carrion

**Comment by jonrwebb** [comment]
I think I would go for the first option for now:


In the first option this will still be 4 levels, shown as
open habitats | short sward & bare ground | habitats | dung and carrion

BTW – Pantheon is looking very good at the moment. I am showing it to the CEO of NE today at 12.

J

**Comment by HDean** [comment]
@johnvanbreda 
What Jon says! Seems like the first option would be the simplest. 
We can look at changing this next FY if a better solution is thought of (it might mean updating the data and term lists, for example, if we were to remove subheadings completely)

**Comment by johnvanbreda** [comment]
Hi @hdean. I've created a view that lists the lexicon content tagged as a subheading just for my own benefit: http://www.brc.ac.uk/pantheon/subheading-resources. 
This lists the following subheadings. 
habitats
soil type
flow
woodland habitat
soil humidity
tree species
conifer or broadleaved 

Having looked at the data I can see some other examples that look like subheadings but aren't tagged as such in the Lexicon, e.g. (there might be more):
sapwood & bark decay (tagged as resource)
shadiness (tagged as a habitat)
shallow freshwater point (not in Lexicon)

Are these tagged incorrectly, or are they really not supposed to be subheadings?

**Comment by HDean** [comment]
@johnvanbreda 
I've double checked with JW and only the ones currently showing as white boxes within the hierarchy diagrams should be subheadings. These are:

base status
humidity
terrestrial aspect
habitats
soil type
flow
woodland habitat
soil humidity
tree species
conifer or broadleaved

The ones you suggested above that might be subheading are not. 

And "shallow freshwater point" should be "shallow freshwater pond"

**Comment by johnvanbreda** [comment]
Thanks. 
I've now updated the tabular report so that subheadings only appear when they are containers for other resources, not on their own.
I've also updated the hierarchy report so subheadings only show the label and are styled differently. I've also styled the other classifications differently so it is clearer.

**Comment by HDean** [comment]
@johnvanbreda 
I can see that the other classifications are styled differently in the hierachy report but not the subheadings - am I missing something?

**Comment by HDean** [comment]
Ignore question above. Other classifications have been moved to a new button.
