### ISSUE TITLE
some species have no Broad Biotope association - all should have

### ISSUE THREAD

**Issue by jonrwebb** [BiologicalRecordsCentre/Pantheon#59]
Hannah said: It appears that some of the SATs are not linked to the broad biotope. I think this is an error in the underlying data. This will take a bit of time to sort out so if it not super urgent will be put on a to-do list for after peer review.

I say: I think that there may also be a number of species that just should be linked to Broad Biotopes and are not

**Comment by johnvanbreda** [comment]
This may relate to the missing links to broad biotope for species which have a habitat within that biotope? I believe Hannah has fixed this in the Pantheon database and I've applied a temporary fix to our copy of the data.

**Comment by HDean** [comment]
Hi @johnvanbreda 
I think this was a separate issue which I have now fixed in the Access database. The one you were thinking of was where some of the tree-associated species were not linked to the tree-associated broad biotopes, which you have fixed.
This is a slightly different one to do with when the SATs were amalgamated into Osiris - I had forgotten to add in some broad biotope. So, if the only trait within Pantheon is the SAT then these species show up without any broad biotope, which should not be the case.
An example would be Carabus (Mesocarabus) problematicus - it has a SAT of F003 but no broad biotope biotope (which it should have - open habitats). I have updated this in the Access database so it should show up correctly after the next data import.
