### ISSUE TITLE
Outputs for dung & carrion, plant association and synanthropic species need adding

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#62]

**Comment by johnvanbreda** [comment]
I’ve had a stab at this and have the dung & carrion entry showing as a starting point. What I’ve done is add any resources that don’t have parents so that they appear in the list of broad biotopes, but place them at the end of the list and make it clear they are other classifications. This seems OK for dung & carrion but looking at the other “other classifications” I can see they are structured in different ways in the data. For example, plant associated is an attribute all of its own rather than existing in the resource hierarchy. Synanthropic and ubiquitous are both tagged as keywords. So, the way I’ve got it set up now is that any keyword, plant-associated, or resource trait that has no parent in the term hierarchy will get shown. 

Does that look OK to you?

**Comment by johnvanbreda** [comment]
Now done I think - the extra classifications are available via the tabular - other button and are included in the hierarchical output.
