### ISSUE TITLE
Conservation status - only show Least Concern where GB rarity status is NS

### ISSUE THREAD

**Issue by HDean** [BiologicalRecordsCentre/Pantheon#65]
•	In the Species Index, the conservation status Least Concern does show
•	In Osiris reporting, the conservation status Least Concern does not show – this applies to all the Red List statuses.
•	However! In the Osiris reporting, if the conservation status is Least Concern and the species also has a Great Britain Rarity Status of NS then both Least Concern and NS should show.

**Comment by johnvanbreda** [comment]
@HDean, I'm not entirely clear what is needed here. Are the first 2 bullet points statements as to what you think already happens, or statements as to what should happen but does not yet? i.e. LC should be shown on the species index, but hidden on the Osiris tables unless it is also NS?

**Comment by HDean** [comment]
HI @johnvanbreda ,
Sorry, should have been more specific! The first 2 bullet points statements are what should happen but does not yet. So, LC should be shown on the species index, but hidden on the Osiris tables unless it is also NS.

**Comment by johnvanbreda** [comment]
@hdean, just to confirm - for sample http://www.brc.ac.uk/pantheon/osiris/tabular?dynamic-conservation_group_id=&dynamic-sample_id=545483 the biotopes table for tree associated shows 4 LC & 3 NS. It could be that these are referring to 7 different species. If the species which have LC were different to the species which have NS, then nothing would be counted at all? Or, in this case if the 3 NS species are the same as 3 of the LC species, then we'd actually show 3 LC and 3NS (because one of the LC must not have an NS associated with it).

**Comment by HDean** [comment]
I've asked JW for confirmation.

**Comment by HDean** [comment]
Hi @johnvanbreda 
I've spoken to JW about this. If the 4 LC species and 3 NS species were different, only the 3 NS species would show. If the 3 NS species were also 3 of the 4 LC species, then the 3 NS species would show but not the remaining LC species.
I think the easiest way to say this would be:
NS always shows and species are counted.
LC does not show and species are not counted.
Sometimes species have a conservation status of NS and LC so only NS needs to show.

NB - this only applies to the Osiris output. The species index should show all conservation statuses, including LC.

**Comment by johnvanbreda** [comment]
Sorry @hdean, I think I'm being a bit slow on this. Your statement in the last post:

> Sometimes species have a conservation status of NS and LC so only NS needs to show.

seems to contradict the first post:

> However! In the Osiris reporting, if the conservation status is Least Concern and the species also has a Great Britain Rarity Status of NS then both Least Concern and NS should show.

If the last post is right, then I don't understand the interact between NS and LC. If a species is LC & NS, then if we only show NS aren't we just saying that LC can be completely ignored in all cases? I.e. the output is the same whether or not LC is present for that species?

As an example, if I have the following species linked to a row on the Osiris broad biotope table for example:

- Species 1: NS
- Species 2: LC
- Species 3: NS & LC
- Species 4: no designations

The conservation output for this row will just be "2 NS" according to your last comment. That's the same whether or not LC is present I think. According to the first comment, I think that this will output "2 NS, 1 LC" because the LC does get shown when it coincides with NS. 
Which approach is correct?

**Comment by HDean** [comment]
Hi @johnvanbreda 
You can ignore what I originally wrote as I think I was just being a bit slow!
Yes, we are saying that within "Habitats and resources" reporting LC can be completely ignored in all cases.
In your example above, the reporting would show "2 NS".
Hopefully this clarifies it...

**Comment by johnvanbreda** [comment]
@hdean Yes, that's much clearer now.
One last clarification (sorry!) - the first post implies that we are dropping ALL red list statuses (EN, NT, DD, RE, VU, LC, CE, NE) not just LC. Is that correct?

**Comment by HDean** [comment]
@johnvanbreda , I see what you mean! Incorrect note by me! It should be from all the Red Lists (there are three in the dataset - global, European and UK).
It is only LC that should be dropped, all other red list statuses remain.

**Comment by johnvanbreda** [comment]
Fixed.
