### ISSUE TITLE
Visualise guild analyses as a pie chart

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/Pantheon#9]
2 pie charts (adult and larval), showing the number of types in the legend.

NE to provide example chart to illustrate required visualisation

**Comment by johnvanbreda** [comment]
See notes from meeting on 17/05.

**Comment by johnvanbreda** [comment]
Here's an example: http://www.brc.ac.uk/pantheon/summary/ecological-guilds?dynamic-sample_id=536582

**Comment by HDean** [comment]
HI @johnvanbreda,

Looks good to me. Couple of things - can the same colours be used for the same guild, e.g. in the above example herbivore for adult is a different colour from herbivore for larva.

Is it also possible, in the table view, to have adult and larva separate?

**Comment by johnvanbreda** [comment]
Doing the pie colours so that they are consistent for each guild isn't completely trivial - probably a few hours work, so I'll leave that one unless you come back and confirm it's worth the effort.

I could split the table into 2 tables - either one above the other, or on 2 separate table like the pies are currently. Or, I could just set the default sort so that it is done on stage first, then count, rather than just count. Let me know what you'd prefer.

**Comment by HDean** [comment]
Hi @johnvanbreda 
I would go with the second option - sort by stage, then count (rather then two separate tables).

**Comment by johnvanbreda** [comment]
Done. Are you happy with the pie chart colours? If so this can be closed?

**Comment by johnvanbreda** [comment]
Wrong button...

**Comment by HDean** [comment]
I am happy with the colours
